@startuml
actor "Eleitor/Candidato" as Usuario
participant "UEg: Gerenciamento" as UEg

Usuario -> UEg : Solicita cadastro (dados pessoais)
UEg -> UEg : Valida dados e verifica existência de cadastro
alt Cadastro não existe
    UEg -> UEg : Realiza cadastro
    UEg -> Usuario : Informa sucesso no cadastro
else Já cadastrado
    UEg -> Usuario : Informa falha (já cadastrado)
end
@enduml
