@startuml
actor "Sistema Externo" as SE
participant "UEg: Gerenciamento" as UEg
participant "UEv" as UEv

SE -> UEg : Solicita listas atualizadas
UEg -> UEv : Buscar listas de candidatos e eleitores
UEv --> UEg : Retorna listas
UEg -> SE : Retorna listas para consulta
@enduml
