@startuml
actor "Eleitor" as Eleitor
participant "UEv: Votação" as UEV

Eleitor -> UEV : Solicita iniciar votação
UEV -> UEV : Verifica se o eleitor pode votar
alt Eleitor pode votar
    UEV -> Eleitor : Exibe opções de voto
    Eleitor -> UEV : Seleciona opção de voto
    UEV -> UEV : Registra voto
    UEV -> Eleitor : Mensagem de sucesso
else Eleitor já votou
    UEV -> Eleitor : Informa bloqueio de votação
end
@enduml
